# EntiDB Analysis Options
#
# This file configures static analysis for EntiDB.
# Uses strict linting rules for production-quality code.
#
# For more information, see:
# - https://dart.dev/go/core-lints
# - https://dart.dev/guides/language/analysis-options

include: package:lints/recommended.yaml

analyzer:
  # Treat all warnings as errors in CI
  errors:
    # Promote important warnings to errors
    missing_return: error
    dead_code: warning
    unused_import: warning
    unused_local_variable: warning
    
  # Enable stricter type checking
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  # Exclude generated files and build outputs
  exclude:
    - "**/*.g.dart"
    - "build/**"
    - ".dart_tool/**"

linter:
  rules:
    # ==========================================================================
    # Error Prevention
    # ==========================================================================
    
    # Avoid empty catch blocks that swallow errors silently
    - avoid_empty_else
    - empty_catches
    - empty_statements
    
    # Null safety
    - null_check_on_nullable_type_parameter
    - unnecessary_null_checks
    - unnecessary_nullable_for_final_variable_declarations
    
    # Type safety
    - avoid_dynamic_calls
    - avoid_returning_null_for_void
    - collection_methods_unrelated_type
    - unrelated_type_equality_checks
    
    # Async correctness
    - avoid_slow_async_io
    - unawaited_futures
    - discarded_futures
    
    # ==========================================================================
    # Code Style & Readability
    # ==========================================================================
    
    # Naming conventions
    - camel_case_types
    - constant_identifier_names
    - file_names
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    
    # Documentation
    - package_api_docs
    - public_member_api_docs
    - slash_for_doc_comments
    
    # Code organization
    - directives_ordering
    - library_annotations
    - sort_constructors_first
    - sort_unnamed_constructors_first
    
    # Prefer modern syntax
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_function_declarations_over_variables
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    
    # Avoid anti-patterns
    - avoid_catching_errors
    - avoid_function_literals_in_foreach_calls
    - avoid_multiple_declarations_per_line
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_types_on_closure_parameters
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    
    # ==========================================================================
    # Performance
    # ==========================================================================
    
    - avoid_slow_async_io
    - prefer_contains
    - use_string_buffers
    
    # ==========================================================================
    # Maintainability
    # ==========================================================================
    
    # Explicit is better
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters
    - annotate_overrides
    - type_annotate_public_apis
    
    # Code structure
    - cascade_invocations
    - join_return_with_assignment
    - no_adjacent_strings_in_list
    - no_runtimeType_toString
    - one_member_abstracts
    - only_throw_errors
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_constructors_over_static_methods
    - prefer_mixin
    - provide_deprecation_message
    - recursive_getters
    - require_trailing_commas
    - throw_in_finally
    - tighten_type_of_initializing_formals
    - type_init_formals
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_breaks
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_late
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unnecessary_to_list_in_spreads
    - use_decorated_box
    - use_enums
    - use_function_type_syntax_for_parameters
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_raw_strings
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_in_part_of_directives
    - use_super_parameters
    - use_test_throws_matchers
    - use_to_and_as_if_applicable
    
    # ==========================================================================
    # Disabled Rules (with justification)
    # ==========================================================================
    
    # Disabled: Example files and benchmarks need print statements
    # - avoid_print  # Re-enable for lib/ only if needed
    
    # Disabled: Some APIs benefit from positional booleans (e.g., flag parameters)
    # - avoid_positional_boolean_parameters
