/// Product Entity
///
/// Demonstrates how to define an entity for EntiDB storage.
import 'package:entidb/entidb.dart';

/// A product entity for an e-commerce application.
///
/// Implements [Entity] to enable storage in EntiDB collections.
///
/// ## Example
///
/// ```dart
/// final product = Product(
///   name: 'Laptop',
///   description: 'High-performance laptop',
///   price: 999.99,
///   quantity: 10,
///   tags: ['electronics', 'computers'],
/// );
///
/// // Insert into collection
/// final id = await products.insert(product);
/// ```
class Product implements Entity {
  @override
  final String? id;

  /// The product name.
  final String name;

  /// Detailed product description.
  final String description;

  /// Price in dollars.
  final double price;

  /// Available quantity in stock.
  final int quantity;

  /// Searchable tags for categorization.
  final List<String> tags;

  /// When the product was added to the catalog.
  final DateTime createdAt;

  /// Creates a new product.
  ///
  /// The [id] is typically null for new products and will be
  /// auto-generated by EntiDB upon insertion.
  Product({
    this.id,
    required this.name,
    required this.description,
    required this.price,
    this.quantity = 0,
    this.tags = const [],
    DateTime? createdAt,
  }) : createdAt = createdAt ?? DateTime.now();

  /// Serializes the product to a map for storage.
  ///
  /// Note: The [id] is NOT included as EntiDB manages it separately.
  @override
  Map<String, dynamic> toMap() => {
    'name': name,
    'description': description,
    'price': price,
    'quantity': quantity,
    'tags': tags,
    'createdAt': createdAt.toIso8601String(),
  };

  /// Deserializes a product from storage.
  ///
  /// This factory is passed to [Collection] to reconstruct entities.
  static Product fromMap(String id, Map<String, dynamic> map) {
    return Product(
      id: id,
      name: map['name'] as String,
      description: map['description'] as String,
      price: (map['price'] as num).toDouble(),
      quantity: map['quantity'] as int? ?? 0,
      tags: List<String>.from(map['tags'] as List? ?? []),
      createdAt: DateTime.parse(map['createdAt'] as String),
    );
  }

  /// Creates a copy with modified fields.
  ///
  /// Useful for updates since entities are immutable.
  Product copyWith({
    String? id,
    String? name,
    String? description,
    double? price,
    int? quantity,
    List<String>? tags,
    DateTime? createdAt,
  }) {
    return Product(
      id: id ?? this.id,
      name: name ?? this.name,
      description: description ?? this.description,
      price: price ?? this.price,
      quantity: quantity ?? this.quantity,
      tags: tags ?? this.tags,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  @override
  String toString() =>
      'Product(id: $id, name: $name, price: \$$price, qty: $quantity)';
}
